check if x_new is in the span of vectors:
the x_new should be written as a linear combination of vectors to be in the span of vectors.
so, create an augmented matrix and check if it has a solution.
if rank(A) == rank(A|b) => has a solution
if rank(A) < rank(A|b) => no solution


In [36]:
def solve_augmented_matrix(vectors, v):
    A = np.array(vectors)
    # convert A to a column vector
    A = A.T
    b = np.array(v)
    # print(b)
    aug_matrix = np.concatenate((A, b.reshape(-1, 1)), axis=1)
    print(aug_matrix)
    # print(b.reshape(-1, 1))
    rank_A = linalg.matrix_rank(A)
    rank_aug_matrix = linalg.matrix_rank(aug_matrix)
    if rank_A == rank_aug_matrix:
        return "YES"
    else:
        vectors.append(v)
        return "NO"

find projection of A onto B

In [16]:
def projection(A, B):
    A = np.array(A)
    B = np.array(B)
    proj = (np.dot(A, B) / np.dot(B, B)) * B
    return proj

using Gram-Schmidt process, find the orthonormal basis for the vectors

In [17]:
def GramSchmidt(vectors):
    b_prime = [vectors[0]]
    for i in range(1, len(vectors)):
        v = vectors[i]
        for j in range(i):
            v = v - projection(v, b_prime[j])
        b_prime.append(v)
    # normalize the vectors
    b_prime = [v / linalg.norm(v) for v in b_prime]
    return b_prime

Input

In [37]:
import numpy as np
from numpy import linalg

n = int(input())
m = int(input())
# vectors are in R^n space
vectors = []
for i in range(m):
    vector = list(map(int, input().split()))
    vectors.append(vector)
    
x_new = list(map(int, input().split()))

Output

In [41]:
print(solve_augmented_matrix(vectors, x_new))
orthonormal_basis = GramSchmidt(vectors)
for v in orthonormal_basis:
    print(v)
    

[[1 1 1 1]
 [1 2 1 1]
 [1 2 0 0]]
YES
[0.57735027 0.57735027 0.57735027]
[-0.81649658  0.40824829  0.40824829]
[ 0.          0.70710678 -0.70710678]
