In [1]:
import numpy as np

m = int(input("Enter the number of rows(m): "))
n = int(input("Enter the number of columns(n): "))

print("Enter the elements of the matrix: ")
matrix = []
for i in range(m):
    a = input()
    matrix.append(list(map(float, a.split())))


Enter the elements of the matrix: 


In [2]:
def row_echelon_form(matrix, m, n, ref_matrix):
    # if matrix == 0, return 0
    if np.all(matrix == 0):
        ref_matrix = np.vstack((ref_matrix, matrix))
        return ref_matrix
    # find leftmost non-zero column
    pivot_col = 0
    for i in range(n):
        if matrix[0][i] != 0:
            pivot_col = i
            break
    # divide the row by the pivot element to achieve one in the pivot position
    matrix[0] = matrix[0] / matrix[0][pivot_col]
    # eliminate(zero) the elements below the pivot element
    for i in range(1, m):
        matrix[i] = matrix[i] - matrix[i][pivot_col] * matrix[0]
    # add the first row to the ref_matrix, change -0 to 0
    try:
        matrix[0] = np.where(matrix[0] == -0, 0, matrix[0])
        ref_matrix = np.vstack((ref_matrix, matrix[0]))
    except ValueError:
        # to make sure the dimensions of the matrices are the same
        ref_matrix = matrix[0]
    # recursively call the function to the sub-matrix
    return row_echelon_form(matrix[1:], m-1, n, ref_matrix)

print("Row Echelon Form of the matrix is: ")
echelon_form = row_echelon_form(np.array(matrix), m, n, np.array([]))
for row in echelon_form:
    print(row)


Row Echelon Form of the matrix is: 
[1.  0.5 0.5]
[0. 1. 0.]
[0. 0. 1.]


In [3]:
def find_rank(ref_matrix):
    rank = 0
    for row in ref_matrix:
        if not np.all(row == 0):
            rank += 1
    return rank
print("Rank of the matrix is: ", find_rank(row_echelon_form(np.array(matrix), m, n, np.array([]))))


Rank of the matrix is:  3
